In [1]:
import numpy as np


# Q1. Create a NumPy 1-D array with 5 elements
# and perform basic operations

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:", arr)
print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)


# Q2(a). Reverse the NumPy array

arr = np.array([1, 2, 3, 6, 4, 5])

print("\nOriginal Array:", arr)
print("Reversed Array:", arr[::-1])


# Q2(b)(i). Find the most frequent value and its indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)

most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("\nArray x:", x)
print("Most Frequent Value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)


# Q2(b)(ii). Find the most frequent value and its indices

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("\nArray y:", y)
print("Most Frequent Value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)


# Q3. Access elements of a 2-D array

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("\n2-D Array:")
print(arr)

print("1st Row, 2nd Column:", arr[0, 1])
print("3rd Row, 1st Column:", arr[2, 0])


# Q4. Create 1-D array named Riya using linspace()

Riya = np.linspace(10, 100, 25)

print("\nArray Riya:")
print(Riya)

print("Number of Dimensions:", Riya.ndim)
print("Shape:", Riya.shape)
print("Total Elements:", Riya.size)
print("Data Type:", Riya.dtype)
print("Total Bytes Consumed:", Riya.nbytes)

reshaped_Riya = Riya.reshape(5, 5)

print("\nReshaped Riya Array:")
print(reshaped_Riya)

print("\nTranspose using transpose():")
print(reshaped_Riya.transpose())

print("\nTranspose using T:")
print(reshaped_Riya.T)


# Q5. Create a 2-D array named ucs420_Riya

ucs420_Riya = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("\nOriginal ucs420_Riya Array:")
print(ucs420_Riya)

print("Mean:", np.mean(ucs420_Riya))
print("Median:", np.median(ucs420_Riya))
print("Maximum:", np.max(ucs420_Riya))
print("Minimum:", np.min(ucs420_Riya))
print("Unique Elements:", np.unique(ucs420_Riya))


# Reshape into 4 rows and 3 columns

reshaped_ucs420_Riya = ucs420_Riya.reshape(4, 3)

print("\nReshaped ucs420_Riya Array:")
print(reshaped_ucs420_Riya)


# Resize into 2 rows and 3 columns

resized_ucs420_Riya = np.resize(ucs420_Riya, (2, 3))

print("\nResized ucs420_Riya Array:")
print(resized_ucs420_Riya)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]

Array x: [1 2 3 4 5 1 2 1 1 1]
Most Frequent Value: 1
Frequency: 5
Indices: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most Frequent Value: 1
Frequency: 3
Indices: [0 1 2]

2-D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st Row, 2nd Column: 20
3rd Row, 1st Column: 70

Array Riya:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Number of Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200

Reshaped Riya Array:
[[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]

Transp